version: "3.9"
services:
  engine:
    build:
      context: ./engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: 1

  webapp:
    build:
      context: .
      dockerfile: front/cusymint_app/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - engine
    