version: "3.9"
services:
  engine:
    build:
      context: ./engine
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: 1

  web_app:
    build:
      context: .
      dockerfile: front/cusymint_app/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - engine
    