version: "3.9"
services:
  engine:
    image: ghcr.io/cusymint/engine:latest
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: 1

  webapp:
    image: ghcr.io/cusymint/client:latest
    ports:
      - "80:80"
    depends_on:
      - engine
    