name: Cusymint
repository: https://github.com/szymon-zygula/cusymint

packages:
  - front/**

ide:
  intellij: false

scripts:
  generate:
    run: |
      melos exec -- \
        "flutter packages pub run build_runner build --delete-conflicting-outputs"
    packageFilters:
      dependsOn: 
        - build_runner

  generate:tr:
    description: Generate static translation files for the specified package
    run: |
      melos exec -- \
        "flutter pub run easy_localization:generate -S assets/translations -O lib/generated && flutter pub run easy_localization:generate -S assets/translations -O lib/generated -f keys -o locale_keys.g.dart"
    packageFilters:
      dirExists:
        - assets/translations
      dependsOn: 
        - easy_localization


  rebuild:icons:
    run: |
      melos exec -- \
        "flutter pub run flutter_launcher_icons:main"
    packageFilters:
      dependsOn: 
        - flutter_launcher_icons
  
  rebuild:splash:
    run: |
      melos exec -- \
        "flutter pub run flutter_native_splash:create"
    packageFilters:
      dependsOn: 
        - flutter_native_splash

  analyze:
    run: melos exec -c 1 -- "dart analyze . --fatal-infos"

  test:unit:all:
    run: melos run test:unit --no-select

  test:unit:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test --no-pub"
    packageFilters:
      dirExists:
        - test
  
  test:integration:
    run: |
      melos exec -c 6 --fail-fast -- \
        "dart test integration_test"
    packageFilters:
      dirExists:
        - integration_test

  format-check:
    run: melos exec flutter format . --set-exit-if-changed

  build:web:
    run: melos exec --fail-fast -- \
      "flutter build web"
    packageFilters:
      dirExists:
        - web
      scope: 'cusymint_app'

  build:linux:
    run: melos exec --fail-fast -- \
      "flutter build linux"
    packageFilters:
      dirExists:
        - linux
      scope: 'cusymint_app'

  build:windows:
    run: melos exec --fail-fast -- \
      "flutter build windows"
    packageFilters:
      dirExists:
        - windows
      scope: 'cusymint_app'


  build:windows:msix:
    run: melos exec --fail-fast -- \
      "flutter pub run msix:create"
    packageFilters:
      dependsOn: 
        - msix
      dirExists:
        - windows
      scope: 'cusymint_app'

  build:android:
    run: melos exec --fail-fast -- \
      "flutter build apk --split-per-abi"
    packageFilters:
      dirExists:
        - android
      scope: 'cusymint_app'
