name: Cusymint
repository: https://github.com/szymon-zygula/cusymint

packages:
  - front/**

ide:
  intellij: false

scripts:
  generate:
    run: |
      melos exec -- \
        "flutter packages pub run build_runner build --delete-conflicting-outputs"
    select-package:
      depends-on: 
        - build_runner

command:
  bootstrap:
    usePubspecOverrides: true
