name: cusymint_ui
description: Cusymints UI.

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^2.0.0
  flutter_math_fork: ^0.6.3+1

  cusymint_assets:
    path: "../cusymint_assets"
  
  cusymint_l10n:
    path: "../cusymint_l10n"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
