name: cusymint_client_json_rpc
description: JSON RPC client for communication with the cusymint engine.

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  json_rpc_2: ^3.0.2

  cusymint_client_interface:
    path: ../cusymint_client_interface

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
