name: cusymint_client_mock
description: Mock of the cusymint client interface. Used for development and testing.

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cusymint_client_interface:
    path: ../cusymint_client_interface

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
