name: cusymint_app
description: Cusymint application

publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_math_fork: ^0.6.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  golden_toolkit: ^0.13.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  