name: cusymint_assets
description: Cusymint's assets.

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.4
  flutter_gen: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.2.0
  flutter_gen_runner: ^5.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/icons/

  fonts:
    - family: MavenPro
      fonts:
        - asset: assets/fonts/MavenPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/MavenPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/MavenPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MavenPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/MavenPro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MavenPro-Black.ttf
          weight: 900

flutter_gen:
  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      class_name: CuAssets
      package_parameter_enabled: true
      