name: cusymint_assets
description: Cusymint's assets.

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.4
  flutter_gen: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.2.0
  flutter_gen_runner: ^5.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/icons/

flutter_gen:
  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      class_name: CuAssets
      package_parameter_enabled: true
      