name: Frontend Tests
on:
  pull_request:
    types: [ labeled ]

jobs:
  tests:
    if: ${{ github.event.label.name == 'front' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Install melos
        run: |
          dart pub global activate melos
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Check melos version
        run: melos --version

      - name: Bootstrap project
        run: melos bootstrap

      - name: Run tests
        run: melos test:unit:all
      
